// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZsaafn7i1tjA2gB9nWUWzFTNz5uRjYtI',
    appId: '1:823965770843:web:f53cbec8f3f0f1175bcb7e',
    messagingSenderId: '823965770843',
    projectId: 'elevateme-gradepredictor',
    authDomain: 'elevateme-gradepredictor.firebaseapp.com',
    storageBucket: 'elevateme-gradepredictor.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8ALbECF4v0g9wvKt-O0Ub9gcOP0oxQ_0',
    appId: '1:823965770843:android:44a86bd2754b073b5bcb7e',
    messagingSenderId: '823965770843',
    projectId: 'elevateme-gradepredictor',
    storageBucket: 'elevateme-gradepredictor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_6yE76Mnj-FaiQ0Z8Rbajb2FNgaD5M3s',
    appId: '1:823965770843:ios:82696c88b8a0b2ea5bcb7e',
    messagingSenderId: '823965770843',
    projectId: 'elevateme-gradepredictor',
    storageBucket: 'elevateme-gradepredictor.appspot.com',
    iosBundleId: 'com.elevatemeofficial.gp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_6yE76Mnj-FaiQ0Z8Rbajb2FNgaD5M3s',
    appId: '1:823965770843:ios:82696c88b8a0b2ea5bcb7e',
    messagingSenderId: '823965770843',
    projectId: 'elevateme-gradepredictor',
    storageBucket: 'elevateme-gradepredictor.appspot.com',
    iosBundleId: 'com.elevatemeofficial.gp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZsaafn7i1tjA2gB9nWUWzFTNz5uRjYtI',
    appId: '1:823965770843:web:e3bcd99e25546ea35bcb7e',
    messagingSenderId: '823965770843',
    projectId: 'elevateme-gradepredictor',
    authDomain: 'elevateme-gradepredictor.firebaseapp.com',
    storageBucket: 'elevateme-gradepredictor.appspot.com',
  );
}
